# Generated by Django 5.2 on 2025-07-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-time_created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='time_create',
            new_name='time_created',
        ),
    ]
