# Generated by Django 5.2 on 2025-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
        ('users', '0005_viewhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name': 'История просмотра товаров'},
        ),
        migrations.AddConstraint(
            model_name='viewhistory',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_view_product'),
        ),
        migrations.AlterModelTable(
            name='viewhistory',
            table='viewhistory',
        ),
    ]
