# Generated by Django 5.2 on 2025-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
        ('users', '0006_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_review_on_product'),
        ),
    ]
