# Generated by Django 5.2 on 2025-07-07 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_viewhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ('-time_created',), 'verbose_name': 'История просмотра товаров'},
        ),
        migrations.RemoveConstraint(
            model_name='viewhistory',
            name='unique_user_view_product',
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата просмотра'),
            preserve_default=False,
        ),
    ]
