# Generated by Django 5.2 on 2025-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=True),
        ),
    ]
