# Generated by Django 5.2 on 2025-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='processing', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
