# Generated by Django 5.2 on 2025-06-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
