# Generated by Django 5.2 on 2025-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
