# Generated by Django 5.2 on 2025-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(default=0, verbose_name='Средняя оценка товара'),
        ),
    ]
