# Generated by Django 5.2 on 2025-07-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
    ]
